// Task 5 acceptance: lua-seri compatibility.
// 1. unpack the Lua-generated reference file (seri-tool gen) and assert values
// 2. repack the same sequence: byte-exact vs the reference (scalars+array table)
// 3. write a JS-packed file for seri-tool dump inspection
// 4. PTYPE_LUA roundtrip between two JS services (ArrayBuffer payloads)

const io = require("../../js/internal/fs-core.js");

const seriBH = skynetcore.runtime.intCommand("LAUNCH", "snjs test/service/seri-worker.js");
skynet.register("main");
skynetcore.runtime.intCommand("LAUNCH", "driver .main 300 start 0");

function check(cond, name) {
    if (!cond) skynetcore.runtime.error("SERI FAIL: " + name);
    return !!cond;
}

skynet.start(() => {
    skynet.dispatch("text", async (msg) => {
        if (msg !== "start") return "OK";

        const ref = new Uint8Array(io.readFile("build/seri-ref.bin"));
        const vals = skynet.unpack(ref.buffer);
        let ok = true;
        ok = check(vals[0] === null, "nil") && ok;
        ok = check(vals[1] === true, "bool true") && ok;
        ok = check(vals[2] === false, "bool false") && ok;
        ok = check(vals[3] === 0, "int 0") && ok;
        ok = check(vals[4] === 1, "int 1") && ok;
        ok = check(vals[5] === 200, "int 200") && ok;
        ok = check(vals[6] === 70000, "int 70000") && ok;
        ok = check(vals[7] === -1234567, "int -1234567") && ok;
        ok = check(vals[8] === 5000000000n, "qword bigint") && ok;
        ok = check(vals[9] === 1.5, "real 1.5") && ok;
        ok = check(vals[10] === 0.25, "real 0.25") && ok;
        ok = check(vals[11] === "hello", "string") && ok;
        ok = check(vals[12] === "x".repeat(100), "long string") && ok;
        const t1 = vals[13];
        skynetcore.runtime.error("SERI t1 = " + JSON.stringify(t1 && [...t1.entries()]));
        ok = check(t1 instanceof LuaTable, "array table is LuaTable") && ok;
        ok = check(t1.array[0] === 10 && t1.array[1] === 20 && t1.array[2] === 30, "LuaTable array segment 0-based") && ok;
        // .get mirrors Lua t[k] (1-based)
        ok = check(t1.get(1) === 10 && t1.get(2) === 20 && t1.get(3) === 30, "LuaTable .get 1-based") && ok;
        ok = check(t1.len === 3 && t1.array.length === 3, "LuaTable .len") && ok;
        // array-only table: hash segment empty (no index-base flip)
        ok = check(t1.hash instanceof Map && t1.hash.size === 0, "array-only LuaTable empty hash") && ok;
        ok = check(JSON.stringify(t1) === '{"1":10,"2":20,"3":30}', "LuaTable toJSON") && ok;

        // byte-exact roundtrip: same value sequence repacked must equal the
        // Lua-generated bytes (scalars + array table are order-stable)
        const repacked = new Uint8Array(skynet.pack(
            vals[0], vals[1], vals[2], vals[3], vals[4], vals[5], vals[6],
            vals[7], vals[8], vals[9], vals[10], vals[11], vals[12], [10, 20, 30]));
        let byteEq = repacked.length === ref.length;
        if (byteEq) {
            for (let i = 0; i < ref.length; i++) {
                if (repacked[i] !== ref[i]) { byteEq = false; break; }
            }
        }
        ok = check(byteEq, "byte-exact roundtrip (len " + repacked.length + " vs " + ref.length + ")") && ok;

        // JS -> file, later inspected with: test/seri-tool dump build/seri-js.bin
        io.writeFile("build/seri-js.bin", skynet.pack(
            "two", 1, new Map([["k", 5n], ["pi", 3.14]]), [1, new Map()]));
        skynetcore.runtime.error("SERI wrote build/seri-js.bin");

        // PTYPE_LUA roundtrip between two JS services
        const sent = skynet.pack("msg", 42, [1, 2]);
        skynetcore.runtime.error("SERI sent bytes: " + JSON.stringify(Array.from(new Uint8Array(sent))));
        const back = await skynet.call(seriBH, "lua", sent);
        skynetcore.runtime.error("SERI back bytes: " + JSON.stringify(Array.from(new Uint8Array(back))));
        const rb = skynet.unpack(back);
        skynetcore.runtime.error("SERI rb = " + JSON.stringify(rb.map(v => v instanceof Map ? [...v.entries()] : (typeof v === "bigint" ? v.toString() + "n" : v))));
        ok = check(rb[0] === "seri_b_ok" && rb[1] === 43 && rb[2] instanceof LuaTable &&
            rb[2].get(1) === 1 && rb[2].get(2) === 2, "lua protocol roundtrip") && ok;

        // empty [] / {} / new Map() are byte-identical (06 00) and all decode
        // to an empty LuaTable (no collapse ambiguity, no lost arrayness)
        const empties = skynet.unpack(skynet.pack([], {}, new Map()));
        ok = check(empties.length === 3, "empties count") && ok;
        for (let i = 0; i < 3; i++) {
            ok = check(empties[i] instanceof LuaTable && empties[i].array.length === 0 &&
                empties[i].hash.size === 0, "empty table " + i + " is empty LuaTable") && ok;
        }

        // integer-keyed hash survives via LuaTable.hash (number keys stay numbers)
        const ikt = new LuaTable([], new Map([[2, "a"], [5, "b"]]));
        const iktBack = skynet.unpack(skynet.pack(ikt))[0];
        ok = check(iktBack instanceof LuaTable && iktBack.hash.get(2) === "a" &&
            iktBack.hash.get(5) === "b" && iktBack.array.length === 0, "integer-keyed hash roundtrip") && ok;

        // mixed table: array segment + hash segment, lossless roundtrip
        const mixed = new LuaTable([10, 20], new Map([["x", 1]]));
        const mixedBack = skynet.unpack(skynet.pack(mixed))[0];
        ok = check(mixedBack instanceof LuaTable && mixedBack.get(1) === 10 &&
            mixedBack.get(2) === 20 && mixedBack.hash.get("x") === 1, "mixed LuaTable roundtrip") && ok;

        skynetcore.runtime.error("SERI RESULT: " + (ok ? "ALL_OK" : "FAILED"));
        return ok ? "SERI_ALL_OK" : "SERI_FAILED";
    });
});
