// skyjs cluster API (Task 6). Protocol-compatible with the original skynet
// cluster: frames are built by cservice/skyclusterd.so, lua-seri payloads are
// produced/consumed here with skynet.pack/unpack.
//
// NC0.7 transition: this is a CJS module installed by the legacy lazy loader
// It is also the require('skyjs/cluster') internal entry.
//
// Usage:
//   cluster.init()                       locate ".clusterd" (must be launched)
//   cluster.setNodes({ n1: "ip:port" })  declare remote node addresses
//   cluster.open(port)                   accept remote connections
//   cluster.register("name")             publish a local name
//   await cluster.call(node, "@name", ...args)  -> unpacked response values
//   cluster.send(node, "@name", ...args)        one-way
//   await cluster.query(node, "name")    resolve a remote registered name
(function () {
    "use strict";

    const skynetCore = require("../../internal/skynet-core.js");
    const hooks = require("../../internal/runtime-hooks.js");
    const skynetcore = globalThis.skynetcore;
    const PTYPE_TEXT = 0;
    const CLUSTER_TIMEOUT = 3000;  // 30 seconds in centiseconds
    let clusterd = 0;
    const pending = new Map();   // js_session -> { resolve, reject }

    hooks.setClusterHandlers(
        (session, msg) => {
            const p = pending.get(session);
            if (p) {
                pending.delete(session);
                p.resolve(msg);
            }
        },
        (session) => {
            const p = pending.get(session);
            if (p) {
                pending.delete(session);
                p.reject(new Error("cluster.call failed (error response)"));
            }
        }
    );

    function init() {
        clusterd = skynetcore.runtime.intCommand("QUERY", ".clusterd");
        if (!clusterd) throw new Error("cluster: .clusterd not found, launch skyclusterd first");
    }

    // send a command line (+ optional binary payload) to skyclusterd.
    // session must be pre-generated by the caller; throws on send failure.
    function rawCmd(session, line, payloadBytes) {
        const head = new Uint8Array(line.length + 1);
        for (let i = 0; i < line.length; i++) head[i] = line.charCodeAt(i) & 0xff;
        head[line.length] = 10;  // '\n'
        let msg = head;
        if (payloadBytes) {
            msg = new Uint8Array(head.length + payloadBytes.length);
            msg.set(head, 0);
            msg.set(payloadBytes, head.length);
        }
        const r = skynetcore.runtime.send(clusterd, PTYPE_TEXT, msg.buffer, session);
        if (r < 0) {
            throw new Error("cluster: send to clusterd failed");
        }
    }

    // fire-and-forget variant: generates its own session, ignores result
    function rawCmdFire(line) {
        const s = skynetcore.runtime.genId();
        const head = new Uint8Array(line.length + 1);
        for (let i = 0; i < line.length; i++) head[i] = line.charCodeAt(i) & 0xff;
        head[line.length] = 10;  // '\n'
        skynetcore.runtime.send(clusterd, PTYPE_TEXT, head.buffer, s);
    }

    function addrStr(addr) {
        // numeric handles cross as hex strings; names get the '@' prefix
        if (typeof addr === "number") return addr.toString(16);
        return addr.charCodeAt(0) === 64 ? addr : "@" + addr;
    }

    const cluster = {
        init,
        setNodes(obj) {
            for (const k in obj) {
                const sep = obj[k].lastIndexOf(":");
                rawCmdFire("node " + k + " " + obj[k].slice(0, sep) + " " + obj[k].slice(sep + 1));
            }
        },
        open(port) {
            rawCmdFire("listen " + port);
        },
        register(name) {
            rawCmdFire("register " + name);
        },
        call(node, addr, ...vals) {
            const payload = new Uint8Array(skynetcore.seri.pack(...vals));
            return new Promise((resolve, reject) => {
                const session = skynetcore.runtime.genId();
                pending.set(session, {
                    resolve: (ab) => resolve(skynetcore.seri.unpack(ab)),
                    reject,
                });
                try {
                    rawCmd(session, "req " + node + " " + addrStr(addr), payload);
                } catch (e) {
                    pending.delete(session);
                    reject(e);
                    return;
                }
                skynetCore.timeout(CLUSTER_TIMEOUT, () => {
                    if (pending.has(session)) {
                        pending.delete(session);
                        reject(new Error("cluster.call timeout: node=" + node + " addr=" + addr));
                    }
                });
            });
        },
        send(node, addr, ...vals) {
            const payload = new Uint8Array(skynetcore.seri.pack(...vals));
            const s = skynetcore.runtime.genId();
            try {
                rawCmd(s, "push " + node + " " + addrStr(addr), payload);
            } catch (_) {
                // fire-and-forget: log but do not propagate
                skynetcore.runtime.error("cluster.send failed: node=" + node + " addr=" + addr);
            }
        },
        query(node, name) {
            const payload = new Uint8Array(skynetcore.seri.pack(name));
            return new Promise((resolve, reject) => {
                const session = skynetcore.runtime.genId();
                pending.set(session, {
                    resolve: (ab) => resolve(skynetcore.seri.unpack(ab)[0]),
                    reject,
                });
                try {
                    rawCmd(session, "req " + node + " 0", payload);
                } catch (e) {
                    pending.delete(session);
                    reject(e);
                    return;
                }
                skynetCore.timeout(CLUSTER_TIMEOUT, () => {
                    if (pending.has(session)) {
                        pending.delete(session);
                        reject(new Error("cluster.query timeout: node=" + node + " name=" + name));
                    }
                });
            });
        },
    };
    if (typeof module !== "undefined" && module.exports) {
        module.exports = cluster;
    }
})();
